server:
  name: "go-article"
  env: "dev"
  address: ":8080"
  base_url: "https://0d5a-103-157-48-85.ap.ngrok.io"
  internal_access_key: "inikeynya-aman-loh"
database:
  user: "root"
  password: "password"
  host: "localhost"
  port: "3306"
  name: "go-article"
  params: "charset=utf8mb4&parseTime=True&loc=Local"
  migration_table_name: "go-article_migrations"
jwt:
  secret: "go-article_jwt_secret_yang_aman_bgt_deh_pokoknya"
  access_token_expire_hour: 720
  refresh_token_expire_hour: 720
redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0